services:
  flux-ilias-user-import-api:
    ports:
      - 127.0.0.15:80:9501
    image: fluxms/flux-ilias-user-import-api:latest
    environment:
      - EXCEL_IMPORT_DIRECTORY_PATH=/app/data
    volumes:
      - ../../app:/app