<?php

namespace FluxEco\IliasUserApi\Adapters\Config;

enum EnvName: string
{
    case HTTP_ENDPOINT_USER_CREATED = 'HTTP_ENDPOINT_USER_CREATED';
    case HTTP_ENDPOINT_USER_DATA_CHANGED = 'HTTP_ENDPOINT_USER_DATA_CHANGED';
    case HTTP_ENDPOINT_ADDITIONAL_FIELD_VALUE_ADDED = 'HTTP_ENDPOINT_ADDITIONAL_FIELD_VALUE_ADDED';
    case HTTP_ENDPOINT_ADDITIONAL_FIELD_VALUE_CHANGED = 'HTTP_ENDPOINT_ADDITIONAL_FIELD_VALUE_CHANGED';
    case HTTP_ENDPOINT_ADDITIONAL_FIELD_VALUE_REMOVED = 'HTTP_ENDPOINT_ADDITIONAL_FIELD_VALUE_REMOVED';
    case HTTP_ENDPOINT_ADDITIONAL_FIELDS_VALUES_CHANGED = 'HTTP_ENDPOINT_ADDITIONAL_FIELDS_VALUES_CHANGED';

    public function toConfigValue() : string|int|array
    {
        return match ($this) {
            EnvName::HTTP_ENDPOINT_USER_CREATED,
            EnvName::HTTP_ENDPOINT_USER_DATA_CHANGED,
            EnvName::HTTP_ENDPOINT_ADDITIONAL_FIELD_VALUE_ADDED,
            EnvName::HTTP_ENDPOINT_ADDITIONAL_FIELD_VALUE_CHANGED,
            EnvName::HTTP_ENDPOINT_ADDITIONAL_FIELD_VALUE_REMOVED,
            EnvName::HTTP_ENDPOINT_ADDITIONAL_FIELDS_VALUES_CHANGED => explode(" ", getenv($this->value))
        };
    }
}